steps:
  - script: yarn start format.and.lint.check
    displayName: 'format and lint check'

  - script: yarn start prepare.electron
    displayName: 'build electron'

  - script: yarn start e2e.ci1.fixtures
    displayName: 'e2e fixtures (ci1)'

  - script: yarn start e2e.ci1
    displayName: 'e2e tests (ci1)'
