name: Setup
description: Setup tasks
inputs:
  node_version: # id of input
    description: 'Version of node to use'
    required: true
    default: '14'
runs:
  using: 'composite'
  steps:
    - name: Derive appropriate SHAs for base and head for `nx affected` commands
      uses: nrwl/nx-set-shas@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ inputs.node_version }}
    - uses: actions/cache@v2
      id: workspace-cache
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ inputs.node_version }}-workspace-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ inputs.node_version }}-workspace-
    - run: yarn install --frozen-lockfile
      shell: bash
