name: Nx Run
description: Start nxcloud ci-run and run tasks

runs:
  using: 'composite'
  steps:
    - name: Starting nx-cloud ci agents
      run: npx nx-cloud start-ci-run
      shell: bash
    - name: Lint
      run: yarn nx run-many --all --parallel --target=lint --max-parallel=3 --configuration=ci
      shell: bash
    - name: Test
      run: yarn nx run-many --all --parallel --target=test --max-parallel=3 --configuration=ci
      shell: bash
    - name: Build
      run: yarn nx run-many --all --parallel --target=build --max-parallel=3 --configuration=ci
      shell: bash
    - name: Stopping nx-cloud ci agents
      run: npx nx-cloud stop-all-agents
      shell: bash
